[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./out"}]

[rpc_endpoints]
optimism = "https://optimism-goerli.publicnode.com"
zora = "https://testnet.rpc.zora.co"
base = "https://goerli.base.org"
mode = "https://sepolia.mode.network/"
